import type { PedigreeEntry } from "@/components/PedigreeTree";

// Pedigree for the 'A' litter (sire Korifey Vanquish x dam Fortuna Freya
// Happy Fly) — source: https://register.kennelliit.ee/dogs/400071
export const A_LITTER_PEDIGREE: PedigreeEntry[] = [
  // Sire's side
  {
    gen: 1,
    side: "sire",
    row: "1 / span 4",
    reg: "KCAX02483802",
    name: "Korifey Vanquish",
  },
  {
    gen: 2,
    side: "sire",
    row: "1 / span 2",
    reg: "RKF4891873",
    name: "Sant Kreal Bellator",
  },
  {
    gen: 2,
    side: "sire",
    row: "3 / span 2",
    reg: "KCAX0901739",
    name: "Saltiga Iz Zoosfery",
  },
  {
    gen: 3,
    side: "sire",
    row: "1",
    reg: "ROI14/162",
    name: "Ebay Del Tibur",
  },
  {
    gen: 3,
    side: "sire",
    row: "2",
    reg: "RKF3392185",
    name: "Sant Kreal Centara",
  },
  {
    gen: 3,
    side: "sire",
    row: "3",
    reg: "LCCLOF281140/12535",
    name: "Gangster Dandias De La Villa Valiano",
  },
  {
    gen: 3,
    side: "sire",
    row: "4",
    reg: "RKF3378173",
    name: "Holland Rose Iz Zoosfery",
  },

  // Dam's side
  {
    gen: 1,
    side: "dam",
    row: "5 / span 4",
    reg: "EST-01040/23",
    name: "Fortuna Freya Happy Fly",
  },
  {
    gen: 2,
    side: "dam",
    row: "5 / span 2",
    reg: "LŠVKD2983/20",
    name: "Teraline El Seras",
  },
  {
    gen: 2,
    side: "dam",
    row: "7 / span 2",
    reg: "LV-DB-1937/18",
    name: "Teraline Gwendolin Happy Fly",
  },
  {
    gen: 3,
    side: "dam",
    row: "5",
    reg: "LOE2369015",
    name: "Legend Goez on Astor",
  },
  {
    gen: 3,
    side: "dam",
    row: "6",
    reg: "RKF4767845",
    name: "Teraline Arwen",
  },
  {
    gen: 3,
    side: "dam",
    row: "7",
    reg: "RKF4162750",
    name: "Teraline Rohan",
  },
  {
    gen: 3,
    side: "dam",
    row: "8",
    reg: "RKF4233638",
    name: "Teraline Sapphira",
  },
];

// Freya
export const FREYA_PEDIGREE: PedigreeEntry[] = [
  // Sire's side
  {
    gen: 1,
    side: "sire",
    row: "1 / span 4",
    reg: "LŠVKD2983/20",
    name: "Teraline El Seras",
  },
  {
    gen: 2,
    side: "sire",
    row: "1 / span 2",
    reg: "LOE2369015",
    name: "Legend Goez on Astor",
  },
  {
    gen: 2,
    side: "sire",
    row: "3 / span 2",
    reg: "RKF4767845",
    name: "Teraline Arwen",
  },
  {
    gen: 3,
    side: "sire",
    row: "1",
    reg: "RKF29697/21",
    name: "Sant Kreal Idol",
  },
  {
    gen: 3,
    side: "sire",
    row: "2",
    reg: "LOE2131507",
    name: "Uruk-Hai Urissa del Jardin de Elfos",
  },
  {
    gen: 3,
    side: "sire",
    row: "3",
    reg: "LOE2183516",
    name: "Kronos's del valle de Las Aguilas",
  },
  {
    gen: 3,
    side: "sire",
    row: "4",
    reg: "RKF3562252",
    name: "Teraline Insolence",
  },

  // Dam's side
  {
    gen: 1,
    side: "dam",
    row: "5 / span 4",
    reg: "LV-DB-1937/18",
    name: "Teraline Gwendolin Happy Fly",
  },
  {
    gen: 2,
    side: "dam",
    row: "5 / span 2",
    reg: "RKF4162750",
    name: "Teraline Rohan",
  },
  {
    gen: 2,
    side: "dam",
    row: "7 / span 2",
    reg: "RKF4233638",
    name: "Teraline Sapphira",
  },
  {
    gen: 3,
    side: "dam",
    row: "5",
    reg: "LOF84394/10768",
    name: "Destiny's Phoenix Highway to Hell",
  },
  {
    gen: 3,
    side: "dam",
    row: "6",
    reg: "RKF2943971",
    name: "Teraline Ferra",
  },
  {
    gen: 3,
    side: "dam",
    row: "7",
    reg: "UKU0034925",
    name: "Oksamit de Grande Vinko",
  },
  {
    gen: 3,
    side: "dam",
    row: "8",
    reg: "RKF2323110",
    name: "Teraline Montera",
  },
];

// Sirius
export const SIRIUS_PEDIGREE: PedigreeEntry[] = [
  // Sire's side
  {
    gen: 1,
    side: "sire",
    row: "1 / span 8",
    reg: "FI19437/13",
    name: "DENWEST UNIQUE DREAM",
  },
  {
    gen: 2,
    side: "sire",
    row: "1 / span 4",
    reg: "FI15731/10",
    name: "DINICO UNICO DEL CONTE DRAGO",
  },
  {
    gen: 2,
    side: "sire",
    row: "5 / span 4",
    reg: "FIN10892/07",
    name: "DENWEST X-MAS DREAM",
  },
  {
    gen: 3,
    side: "sire",
    row: "1 / span 2",
    reg: "DZB116308",
    name: "YGOR VOM KLINGBACH",
  },
  {
    gen: 3,
    side: "sire",
    row: "3 / span 2",
    reg: "FIN19968/04",
    name: "DINICO BRINNA BRIELLE",
  },
  {
    gen: 3,
    side: "sire",
    row: "5 / span 2",
    reg: "FIN19374/04",
    name: "A'DREAMS MAGNUM",
  },
  {
    gen: 3,
    side: "sire",
    row: "7 / span 2",
    reg: "FIN37649/03",
    name: "TAHI-REME YOGOBELLA",
  },
  {
    gen: 4,
    side: "sire",
    row: "5",
    reg: "FIN15301/02",
    name: "A'DREAMS PILOT",
  },
  {
    gen: 4,
    side: "sire",
    row: "6",
    reg: "FIN20298/97",
    name: "A'DREAMS RHEA",
  },
  {
    gen: 4,
    side: "sire",
    row: "7",
    reg: "LOI98/38607",
    name: "ILANE DARAFAL",
  },
  {
    gen: 4,
    side: "sire",
    row: "8",
    reg: "METDOB1628/98",
    name: "TAHI-REME LOLLY",
  },

  // Dam's side
  {
    gen: 1,
    side: "dam",
    row: "9 / span 8",
    reg: "FI30350/16",
    name: "TAIKAVIITAN WALMIS-WASTAUS",
  },
  {
    gen: 2,
    side: "dam",
    row: "9 / span 4",
    reg: "FI41161/15",
    name: "QUIRINUS VON NEMESIS",
  },
  {
    gen: 2,
    side: "dam",
    row: "13 / span 4",
    reg: "FI51533/12",
    name: "TAIKAVIITAN UUSI-UNELMA",
  },
  {
    gen: 3,
    side: "dam",
    row: "9 / span 2",
    reg: "LOI07/54594",
    name: "ALE'ALAMOS DEL CITONE",
  },
  {
    gen: 3,
    side: "dam",
    row: "11 / span 2",
    reg: "VDH/DV125126",
    name: "NOVALIS VON NEMESIS",
  },
  {
    gen: 3,
    side: "dam",
    row: "13 / span 2",
    reg: "FI21069/10",
    name: "SANT KREAL CHE GUEVARA",
  },
  {
    gen: 3,
    side: "dam",
    row: "15 / span 2",
    reg: "FI26093/09",
    name: "TAIKAVIITAN TÄÄLTÄ-TULLAAN",
  },
  {
    gen: 4,
    side: "dam",
    row: "9",
    reg: "LOI05/47687",
    name: "PATHOS DELLE QUERCE NERE",
  },
  {
    gen: 4,
    side: "dam",
    row: "10",
    reg: "LOI01/116325",
    name: "RAMONARASHI DEL CITONE",
  },
  {
    gen: 4,
    side: "dam",
    row: "11",
    reg: "VDH/DZB121484",
    name: "HILO VON NEMESIS",
  },
  {
    gen: 4,
    side: "dam",
    row: "13",
    reg: "RKF2295907",
    name: "GRAND MOLLIS ARMANI",
  },
  {
    gen: 4,
    side: "dam",
    row: "14",
    reg: "RKF1890254",
    name: "SANT KREAL DOMINO",
  },
];

// Sahara
export const SAHARA_PEDIGREE: PedigreeEntry[] = [
  // Sire's side
  {
    gen: 1,
    side: "sire",
    row: "1 / span 4",
    reg: "IKCA74638",
    name: "Ballyfrawley The Show Must Go On",
  },
  {
    gen: 2,
    side: "sire",
    row: "1 / span 2",
    reg: "AKCWS25518101",
    name: "Von Charm's Return Of The King",
  },
  {
    gen: 2,
    side: "sire",
    row: "3 / span 2",
    reg: "IKCA02135",
    name: "Ballyfrawely All This And Heaven Too",
  },
  {
    gen: 3,
    side: "sire",
    row: "1",
    reg: "AKCWS09942704",
    name: "Jerdans Prince Of Vigo",
  },
  {
    gen: 3,
    side: "sire",
    row: "2",
    reg: "AKCWS10146703",
    name: "Shady Creeks Sister Golden Hair",
  },
  {
    gen: 3,
    side: "sire",
    row: "3",
    reg: "KCRCAR0902560",
    name: "Diplomatic's Nicolas Cage Jr To Garsak",
  },
  {
    gen: 3,
    side: "sire",
    row: "4",
    reg: "IKCY88531",
    name: "Ballyfrawely You Could Be Mine",
  },

  // Dam's side
  {
    gen: 1,
    side: "dam",
    row: "5 / span 4",
    reg: "SHSB767139",
    name: "Creed Danes A Star From Sahara",
  },
  {
    gen: 2,
    side: "dam",
    row: "5 / span 2",
    reg: "SHSB707661",
    name: "Captain America Vom Wasaland",
  },
  {
    gen: 2,
    side: "dam",
    row: "7 / span 2",
    reg: "SHSB743343",
    name: "Phillys-F De' Cinegeti",
  },
  {
    gen: 3,
    side: "dam",
    row: "5",
    reg: "AKCWS10839304",
    name: "Maitau's No Bones About It Paesan",
  },
  {
    gen: 3,
    side: "dam",
    row: "6",
    reg: "SHSB666496",
    name: "Love-Dane's Cute Polarqueen",
  },
  {
    gen: 3,
    side: "dam",
    row: "7",
    reg: "ROI13/120980",
    name: "Highesteem Wizard Of Cinegeti",
  },
  {
    gen: 3,
    side: "dam",
    row: "8",
    reg: "LOI12/62813",
    name: "Griselda-F De' Cinegeti",
  },
];
